server:
  port: 8085

spring:
  application:
    name: account

auth-service:
  url: http://localhost:8089

feign:
  httpclient:
    max-connections: 1000000
    max-connections-per-route: 1000000
    connection-timeout: 60000
  client:
    config:
      default:
        connectTimeout: 600000
        readTimeout: 300000
      feignName:
        connectTimeout: 600000
        readTimeout: 300000
        loggerLevel: full
jwt:
  duration: 900 # 15 minutes
  secret: 4An32HWrMUxVr0TH6ZrV6p+g/cT8KCwz34w7h7FdTc6h8mbIvAygs5DcfeiDtqFKm84/t4OeifghoVCBuymmtQ==
  refresh-duration: 604800 # 7 days
